const Images = {
    logo: require('../../assets/logo.png'),
    SignInBackground: require('../../assets/sign-background.png'),
    facebook: require('../../assets/fb.png'),
    instagram: require('../../assets/insta.png'),
    snapchat: require('../../assets/snap_chat.png'),
    twitter: require('../../assets/twitter.png'),
    User_Icon_White: require('../../assets/User_Icon_White.png'),
    activeAccount: require('../../assets/activeAccount.png'),
    favourite: require('../../assets/favourite.png'),
    Reminders: require('../../assets/Reminders.png'),
    My_Contacts: require('../../assets/My_Contacts.png'),
    Orders: require('../../assets/Orders.png'),
    Notification: require('../../assets/Notification.png'),
    Plans: require('../../assets/Plans.png'),
    Contact_Us: require('../../assets/Contact_Us.png'),
    Log_out: require('../../assets/Log_out.png'),
    menu: require('../../assets/Menu.png'),
    activeHome: require('../../assets/activeHome.png'),
    inactiveHome: require('../../assets/inactiveHome.png'),
    inactiveReminders: require('../../assets/inactiveReminders.png'),
    activeContacts: require('../../assets/activeContacts.png'),
    inactiveContacts: require('../../assets/inactiveContacts.png'),
    inactiveOrders: require('../../assets/inactiveOrders.png'),
    inactiveAccount: require('../../assets/inactiveAccount.png'),
    Fav_Fill: require('../../assets/Fav_Fill.png'),
    Fav_Unfill: require('../../assets/Fav_Unfill.png'),
    Filter: require('../../assets/Filter.png'),
    Contacts: require('../../assets/Contacts.png'),
    Giftbox: require('../../assets/Giftbox.png'),
    Subcription_Bg: require('../../assets/Subcription_Bg.png'),
    ProfileEdit: require('../../assets/ProfileEdit.png')
}

export default Images;